CREATE TABLE `sip_users` (
  `id` int(11) NOT NULL auto_increment,
  `name` varchar(80) NOT NULL default '',
  `host` varchar(31) NOT NULL default '',
  `nat` varchar(5) NOT NULL default 'no',
  `type` enum('user','peer','friend') NOT NULL default 'friend',
  `accountcode` varchar(20) default NULL,
  `amaflags` varchar(13) default NULL,
  `call-limit` smallint(5) unsigned default NULL,
  `callgroup` varchar(10) default NULL,
  `callerid` varchar(80) default NULL,
  `cancallforward` char(3) default 'yes',
  `canreinvite` char(3) default 'yes',
  `context` varchar(80) default NULL,
  `defaultip` varchar(15) default NULL,
  `dtmfmode` varchar(7) default NULL,
  `fromuser` varchar(80) default NULL,
  `fromdomain` varchar(80) default NULL,
  `insecure` varchar(4) default NULL,
  `language` char(2) default NULL,
  `mailbox` varchar(50) default NULL,
  `md5secret` varchar(80) default NULL,
  `deny` varchar(95) default NULL,
  `permit` varchar(95) default NULL,
  `mask` varchar(95) default NULL,
  `musiconhold` varchar(100) default NULL,
  `pickupgroup` varchar(10) default NULL,
  `qualify` char(3) default NULL,
  `regexten` varchar(80) default NULL,
  `restrictcid` char(3) default NULL,
  `rtptimeout` char(3) default NULL,
  `rtpholdtimeout` char(3) default NULL,
  `secret` varchar(80) default NULL,
  `setvar` varchar(100) default NULL,
  `disallow` varchar(100) default 'all',
  `allow` varchar(100) default 'g729;ilbc;gsm;ulaw;alaw',
  `fullcontact` varchar(80) NOT NULL default '',
  `ipaddr` varchar(15) NOT NULL default '',
  `port` smallint(5) unsigned NOT NULL default '0',
  `regserver` varchar(100) default NULL,
  `regseconds` int(11) NOT NULL default '0',
  `lastms` int(11) NOT NULL default '0',
  `username` varchar(80) NOT NULL default '',
  `defaultuser` varchar(80) NOT NULL default '',
  `subscribecontext` varchar(80) default NULL,
  `useragent` varchar(20) default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `name_2` (`name`)
) ENGINE=innodb;

CREATE TABLE `iax_users` (
  `name` varchar(30) primary key NOT NULL,
  `username` varchar(30), 
  `type` varchar(6) NOT NULL, 
  `secret` varchar(50), 
  `md5secret` varchar(32), 
  `dbsecret` varchar(100), 
  `notransfer` varchar(10), 
  `inkeys` varchar(100),
  `outkey` varchar(100),
  `auth` varchar(100), 
  `accountcode` varchar(100), 
  `amaflags` varchar(100), 
  `callerid` varchar(100), 
  `context` varchar(100), 
  `defaultip` varchar(15), 
  `host` varchar(31) NOT NULL default 'dynamic', 
  `language` char(5), 
  `mailbox` varchar(50), 
  `deny` varchar(95),
  `permit` varchar(95),  
  `qualify` varchar(4), 
  `disallow` varchar(100), 
  `allow` varchar(100), 
  `ipaddr` varchar(15), 
  `port` integer default 0,
  `regseconds` integer default 0
) engine=innodb;
CREATE UNIQUE INDEX iax_users_idx ON iax_users(username); 

CREATE TABLE `extensions` (
  `id` int(11) NOT NULL auto_increment,
  `context` varchar(20) NOT NULL default '',
  `exten` varchar(20) NOT NULL default '',
  `priority` tinyint(4) NOT NULL default '0',
  `app` varchar(20) NOT NULL default '',
  `appdata` varchar(128) NOT NULL default '',
  PRIMARY KEY  (`context`,`exten`,`priority`),
  KEY `id` (`id`)
) TYPE=innodb; 

CREATE TABLE `meetme` (
  `confno` varchar(80) DEFAULT '0' NOT NULL,
  `pin` varchar(20) NULL,
  `adminpin` varchar(20) NULL,
  `members` integer DEFAULT 0 NOT NULL,
  PRIMARY KEY (confno)
) engine=innodb;
